// <auto-generated />
using System;
using EVChargePlanner.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EVChargePlanner.Infrastructure.Migrations
{
    [DbContext(typeof(EVChargePlannerDbContext))]
    [Migration("20260805104134_AddCarModelCatalog")]
    partial class AddCarModelCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EVChargePlanner.Domain.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BatteryCapacityKWh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxChargingPowerKW")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("EVChargePlanner.Domain.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BatteryCapacityKWh")
                        .HasColumnType("numeric");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxChargingPowerKW")
                        .HasColumnType("numeric");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryCapacityKWh = 57.5m,
                            Brand = "Tesla",
                            MaxChargingPowerKW = 11m,
                            Model = "Model 3"
                        },
                        new
                        {
                            Id = 2,
                            BatteryCapacityKWh = 75m,
                            Brand = "Tesla",
                            MaxChargingPowerKW = 11m,
                            Model = "Model Y"
                        },
                        new
                        {
                            Id = 3,
                            BatteryCapacityKWh = 58m,
                            Brand = "Volkswagen",
                            MaxChargingPowerKW = 11m,
                            Model = "ID.3"
                        },
                        new
                        {
                            Id = 4,
                            BatteryCapacityKWh = 77m,
                            Brand = "Volkswagen",
                            MaxChargingPowerKW = 11m,
                            Model = "ID.4"
                        },
                        new
                        {
                            Id = 5,
                            BatteryCapacityKWh = 60.4m,
                            Brand = "BYD",
                            MaxChargingPowerKW = 11m,
                            Model = "Dolphin"
                        },
                        new
                        {
                            Id = 6,
                            BatteryCapacityKWh = 60.5m,
                            Brand = "BYD",
                            MaxChargingPowerKW = 11m,
                            Model = "Atto 3"
                        },
                        new
                        {
                            Id = 7,
                            BatteryCapacityKWh = 65.4m,
                            Brand = "Hyundai",
                            MaxChargingPowerKW = 11m,
                            Model = "Kona Electric"
                        },
                        new
                        {
                            Id = 8,
                            BatteryCapacityKWh = 77.4m,
                            Brand = "Hyundai",
                            MaxChargingPowerKW = 11m,
                            Model = "Ioniq 5"
                        },
                        new
                        {
                            Id = 9,
                            BatteryCapacityKWh = 18.1m,
                            Brand = "Toyota",
                            MaxChargingPowerKW = 6.6m,
                            Model = "RAV4 Plug-in Hybrid"
                        },
                        new
                        {
                            Id = 10,
                            BatteryCapacityKWh = 18.8m,
                            Brand = "Volvo",
                            MaxChargingPowerKW = 6.4m,
                            Model = "XC60 Recharge"
                        });
                });

            modelBuilder.Entity("EVChargePlanner.Domain.Charger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxPowerKW")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Chargers");
                });

            modelBuilder.Entity("EVChargePlanner.Domain.ChargingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("ChargerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EnergyKWh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ChargerId");

                    b.ToTable("ChargingSessions");
                });

            modelBuilder.Entity("EVChargePlanner.Domain.PriceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerKWh")
                        .HasColumnType("numeric");

                    b.Property<string>("PriceZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TimeStart", "PriceZone")
                        .IsUnique();

                    b.ToTable("PriceRecords");
                });

            modelBuilder.Entity("EVChargePlanner.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EVChargePlanner.Domain.ChargingSession", b =>
                {
                    b.HasOne("EVChargePlanner.Domain.Car", "Car")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVChargePlanner.Domain.Charger", "Charger")
                        .WithMany()
                        .HasForeignKey("ChargerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Charger");
                });

            modelBuilder.Entity("EVChargePlanner.Domain.Car", b =>
                {
                    b.Navigation("ChargingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
